## View(Reshape)
shape 를 다시 만들어서 보여(view) 주겠다.

In [2]:
import numpy as np
import torch

In [4]:
t = np.array(
    [[[0,1,2],
     [3,4,5]],
    [[6,7,8],
    [9,9,9]]
    ])
tt = torch.FloatTensor(t)
print(tt) # 굉장히 보기 복잡하고 다루기도 힘들어 보인다.
print(tt.shape)

tensor([[[0., 1., 2.],
         [3., 4., 5.]],

        [[6., 7., 8.],
         [9., 9., 9.]]])
torch.Size([2, 2, 3])


In [8]:
print(tt.view([-1,3])) # 처음 차원은 잘 모르겠는데 3개의 원소를 가진 차원으로 보여줘라

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.],
        [9., 9., 9.]])


In [14]:
print(tt.view([3])) # 사이즈를 맞춰주어야 함을 알 수 있다. (원소의 갯수를 어떤 차원으로 보일것인가와 관련된 이야기같음)

RuntimeError: shape '[3]' is invalid for input of size 12

In [12]:
print(tt.view([-1,1,3]))
print(tt.view([-1,1,3]).shape)

tensor([[[0., 1., 2.]],

        [[3., 4., 5.]],

        [[6., 7., 8.]],

        [[9., 9., 9.]]])
torch.Size([4, 1, 3])


## Squeeze
dimension 의 element 가 1일때 쥐어짜서 없애줌

In [33]:
ft = torch.FloatTensor([[0,1,2]])
print(f' ft( {ft} )\'s shape : {ft.shape}')
print(f'squeeze : {ft.squeeze()}')
print(f'squeeze (dim=0) : {ft.squeeze(dim=0)}') # shape [1,3] 이어서 dim=0 에 의해 squeeze
print(f'squeeze (dim=1) : {ft.squeeze(dim=1)}') # shape [1,3] 이므로 dim=1 일때 3이므로 결과는 그대로
print('--------------------------')
ft = torch.FloatTensor([[1],[2],[3]])
print(f'ft( {ft} )\'s shape : {ft.shape}')
print(f'squeeze : {ft.squeeze()}')
print(f'squeeze (dim=0) : \n{ft.squeeze(dim=0)}') # shape [3,1] 이어서 dim=0 에 의해 변하는 것이 없음
print(f'squeeze (dim=1) : {ft.squeeze(dim=1)}') # shape [3,1] 이므로 dim=1 에 의해 squeeze

 ft( tensor([[0., 1., 2.]]) )'s shape : torch.Size([1, 3])
squeeze : tensor([0., 1., 2.])
squeeze (dim=0) : tensor([0., 1., 2.])
squeeze (dim=1) : tensor([[0., 1., 2.]])
--------------------------
ft( tensor([[1.],
        [2.],
        [3.]]) )'s shape : torch.Size([3, 1])
squeeze : tensor([1., 2., 3.])
squeeze (dim=0) : 
tensor([[1.],
        [2.],
        [3.]])
squeeze (dim=1) : tensor([1., 2., 3.])


## Unsqueeze
특정 dim 뒤에 1차원을 넣겠다.(view 로서 해도 됨)

In [66]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.shape)

tensor([1., 2., 3.])
torch.Size([3])


In [67]:
print(ft.unsqueeze(dim=0))
print(ft.unsqueeze(dim=0).shape) # dim =0 에 대해 한 차원을 넣음
print(ft.unsqueeze(dim=1))
print(ft.unsqueeze(dim=1).shape) # dim =1 에 대해 한 차원을 넣음

tensor([[1., 2., 3.]])
torch.Size([1, 3])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [71]:
print(ft.view([1,-1]))
print(ft.view([1,-1]).shape) # dim =0 의 차원을 1로 하고 나머지는 알아서
print(ft.view([-1,1]))
print(ft.view([-1,1]).shape) # dim =1 의 차원을 1로 하고 나머지는 알아서

tensor([[1., 2., 3.]])
torch.Size([1, 3])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [72]:
ft = torch.FloatTensor([[1., 2., 3.]])
print(f'original {ft} shape : {ft.shape}')
print(f'2D array ft squeeze to dim=0 : {ft.unsqueeze(dim=0)} shape : {ft.unsqueeze(dim=0).shape}')
print(f'2D array ft squeeze to dim=1 : {ft.unsqueeze(dim=1)} shape : {ft.unsqueeze(dim=1).shape}')
print(f'2D array ft squeeze to dim=2 : {ft.unsqueeze(dim=2)} shape : {ft.unsqueeze(dim=2).shape}')

original tensor([[1., 2., 3.]]) shape : torch.Size([1, 3])
2D array ft squeeze to dim=0 : tensor([[[1., 2., 3.]]]) shape : torch.Size([1, 1, 3])
2D array ft squeeze to dim=1 : tensor([[[1., 2., 3.]]]) shape : torch.Size([1, 1, 3])
2D array ft squeeze to dim=2 : tensor([[[1.],
         [2.],
         [3.]]]) shape : torch.Size([1, 3, 1])


## Type Casting
tensor 의 타입을 바꾸어주는것

In [74]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [78]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [81]:
print((lt==3)) # lt 의 element 중 원소가 3인 값이 있으면 True
print(type(lt==3))

tensor([0, 0, 1, 0], dtype=torch.uint8)
<class 'torch.Tensor'>


## Concatenate

In [101]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[2,3],[4,5]])
print(f'x: {x} \ny : {y}')
print(torch.cat([x,y], dim=0)) #dim=0에 대해 접합이므로 row 로 붙는 모양
print(torch.cat([x,y], dim=0).shape)
print(torch.cat([x,y], dim=1)) #dim=1에 대해 접합이므로 column 로 붙는 모양

x: tensor([[1., 2.],
        [3., 4.]]) 
y : tensor([[2., 3.],
        [4., 5.]])
tensor([[1., 2.],
        [3., 4.],
        [2., 3.],
        [4., 5.]])
torch.Size([4, 2])
tensor([[1., 2., 2., 3.],
        [3., 4., 4., 5.]])


## Stacking
명시한 dimension 으로 쌓는것

In [104]:
x = torch.FloatTensor([1,2]) #size = (2,)
y = torch.FloatTensor([4,5])
z = torch.FloatTensor([7,8])
print(torch.stack([x,y,z])) # stack by dim=0(default)
print(torch.stack([x,y,z]).shape)
print(torch.stack([x,y,z], dim=1)) # stack by dim=1 
print(torch.stack([x,y,z], dim=1).shape)

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])
torch.Size([3, 2])
tensor([[1., 4., 7.],
        [2., 5., 8.]])
torch.Size([2, 3])


In [112]:
# concatenate 를 사용하여 stack 과 같이 구현
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)]))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=1))

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])
tensor([[1., 2., 4., 5., 7., 8.]])


TypeError: view(): argument 'size' must be tuple of ints, but found element of type torch.Size at pos 2