In [10]:
import numpy as np
import torch

## 1D array with numpy

In [4]:
v = np.array([0,1,2,3,4,5,6])
print(v)

[0 1 2 3 4 5 6]


In [5]:
print(f'dim of v : {v.ndim}')
print(f'shape of v : {v.shape}')

dim of v : 1
shape of v : (7,)


In [9]:
#element slicing
print(f'v[0] : {v[0]}, v[1]: {v[1]}, v[-1] : {v[-1]}')
print(f'v[1:] : {v[1:]} v[2:5] : {v[2:5]}')
print(f'v[4:-1] : {v[4:-1]}')

v[0] : 0, v[1]: 1, v[-1] : 6
v[1:] : [1 2 3 4 5 6] v[2:5] : [2 3 4]
v[4:-1] : [4 5]


## 2D array with numpy

In [12]:
m = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
print(m)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
print(f'dim of m : {m.ndim}')
print(f'shape of m : {m.shape}')

dim of m : 2
shape of m : (4, 3)


## 1D array with pytorch

In [14]:
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [18]:
print(f'dim of t : {t.dim()}')
print(f'shape of t : {t.shape}')
print(f'size of t : {t.size()}')

dim of t : 1
shape of t : torch.Size([7])
size of t : torch.Size([7])


In [22]:
print(f't[0] : {t[0]}')
print(f't[-1] : {t[-1]}')
print(f't[:-1] : {t[:-1]}')

t[0] : 0.0
t[-1] : 6.0
t[:-1] : tensor([0., 1., 2., 3., 4., 5.])


## 2D array with pytorch

In [24]:
t = torch.FloatTensor([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
print(t)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])


In [26]:
print(f'dim of t : {t.dim()}')
print(f'shape of t : {t.shape}')
print(f'size of t : {t.size()}')

dim of t : 2
shape of t : torch.Size([4, 3])
size of t : torch.Size([4, 3])


In [31]:
print(f't[:, -1] : {t[:, 1]}') # 첫번째 차원(열)에서는 다 가져오되 두번째 차원(열)에서는 인덱스가 1인 요소들을 가져와라
print(f't[:, :-1] : {t[:,:-1]}') # 첫번째 차원(열)에서는 다 가져오되 두번째 차원(열) 에서는 마지막 차원(열) 까지의 요소들을 가져와라

t[:, -1] : tensor([2., 3., 4., 5.])
t[:, :-1] : tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.]])


## Broadcasting
연산을 하는데 부족한 부분을 자동으로 채워주는것
주의해서 사용해야한다.

In [33]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1+m2)

tensor([5., 5.])


In [34]:
# vector + scalar
m2 = torch.FloatTensor([3]) # 3-> [3 ,3]
print(m1+m2)

tensor([6., 6.])


In [36]:
# another dim vector calculate
# 자동으로 부족한 요소(행,열)이 채워지기 때문에 주의를 요해야 한다.
m1 = torch.FloatTensor([[1,2]]) # dim :(1,2), [[1,2]] -> dim: (2,2), [[1,2], [1,2]]
m2 = torch.FloatTensor([[3],[4]]) # dim : (2,1), [[3],[4]] -> dim:(2,2), [[3,3], [4,4]]
print(m1+m2) # -> [[1,2], [1,2]] + [[3,3], [4,4]]

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication
multiplication : 내적을 구하는 것
matrix multiplication : 성분곱

In [39]:
print('1. Multiplication(inner product)')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[3],[4]])
print(f'shape of matrix 1 : {m1.shape}')
print(f'shape of matrix 2 : {m2.shape}')
print(f'innter product : \n{m1.matmul(m2)}')

1. Multiplication(inner product)
shape of matrix 1 : torch.Size([2, 2])
shape of matrix 2 : torch.Size([2, 1])
innter product : 
tensor([[11.],
        [25.]])


In [41]:
print('2. Matrix Multiplication')
print(f'shape of matrix 1 : {m1.shape}')
print(f'shape of matrix 2 : {m2.shape}')
print(f'element multiplication : \n{m1.mul(m2)}') # 같은 위치에 있는 요소들끼리의 곱
print(m1*m2)

2. Matrix Multiplication
shape of matrix 1 : torch.Size([2, 2])
shape of matrix 2 : torch.Size([2, 1])
element multiplication : 
tensor([[ 3.,  6.],
        [12., 16.]])
tensor([[ 3.,  6.],
        [12., 16.]])


## Mean
해당 텐서의 평균값

In [43]:
t= torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [48]:
# mean calculate float only
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as e:
    print(e)

Can only calculate the mean of floating types. Got Long instead.


In [61]:
t = torch.FloatTensor([[1,2],[3,4]])
print(f'dim of t : {t.dim()}\t shape of t : {t.shape}')
print(f't.mean() : {t.mean()}') # all elements mean
print(f't\'s mean(axis=0) : {t.mean(dim=0)}') # dim -> (0 :row,1 :column)
print(f't\'s mean(axis=1) : {t.mean(dim=1)}')
print(f't\'s mean(axis=-1) : {t.mean(dim=-1)}') # if shape : (1,2,3) => dim = 2

dim of t : 2	 shape of t : torch.Size([2, 2])
t.mean() : 2.5
t's mean(axis=0) : tensor([2., 3.])
t's mean(axis=1) : tensor([1.5000, 3.5000])
t's mean(axis=-1) : tensor([1.5000, 3.5000])


## Sum
해당 텐서의 값들을 더한 값

In [62]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [66]:
print(f't.sum() : {t.sum()}')
print(f't\'s sum(axis=0) : {t.sum(dim=0)}')
print(f't\'s sum(axis=1) : {t.sum(dim=1)}')
print(f't\'s sum(axis=-1) : {t.sum(dim=-1)}') # if shape : (1,2,3) => dim =2 

t.sum() : 10.0
t's sum(axis=0) : tensor([4., 6.])
t's sum(axis=1) : tensor([3., 7.])
t's sum(axis=-1) : tensor([3., 7.])


## Max and Argmax
Max : 가장 큰 값
Argmax : 가장 큰 값의 인덱스값

In [70]:
t = torch.FloatTensor([[1,4],[2,3]])
print(t)

tensor([[1., 4.],
        [2., 3.]])


In [74]:
print(f't\'s max value : {t.max()}')
print(f't\'s max value(axis=0) : {t.max(dim=0)}') # 첫번째 출력은 가장 큰 값들, 두번째 출력은 그 값들의 인덱스(ex 아파트 층) dim=0
print(f't\'s max : {t.max(dim=0)[0]}')
print(f't\'s argmax : {t.max(dim=0)[1]}')

t's max value : 4.0
t's max value(axis=0) : (tensor([2., 4.]), tensor([1, 0]))
t's max : tensor([2., 4.])
t's argmax : tensor([1, 0])


In [76]:
print(f't\'s max value(axis=1) : {t.max(dim=1)}') # 첫번째 출력은 가장 큰 값들, 두번째 출력은 그 값들의 인덱스(ex 아파트 호수) dim=1
print(f't\'s max value(axis=-1, most recently dim) : {t.max(dim=-1)}')

t's max value(axis=1) : (tensor([4., 3.]), tensor([1, 1]))
t's max value(axis=-1, most recently dim) : (tensor([4., 3.]), tensor([1, 1]))
